#!C:\Users\Admin\Desktop\3차프로젝트\fa06-fin-aicc\app\VibeVoice-main\.venv312\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
